project:
  type: website

website:
  title: "Hakyimlab Notes"
  navbar:
    background: "#A9A9A9"
    google-analytics: "G-8SL8WKCMYZ"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hakyimlab/
      - icon: twitter
        href: https://twitter.com/hakyim
  search: 
    location: navbar
    type: overlay
    copy-button: true
format:
  html:
    theme: cosmo
    css: styles.css


