project:
  type: website

website:
  title: "web-lab-notes-quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hakyimlab/
      - icon: twitter
        href: https://twitter.com/hakyim
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

