project:
  type: website

website:
  title: "HakyImLab Notes"
  navbar:
    background: "#A9A9A9"
    google-analytics: "G-8SL8WKCMYZ"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hakyimlab/web-lab-notes-quarto
  search: 
    location: navbar
    type: overlay
    copy-button: true
  
format:
  html:
    theme: cosmo
    css: styles.css

license: "© HakyImLab and Listed Authors - CC BY 4.0 for Text and figures - MIT for code"


