project:
  type: website

website:
  title: "HakyImLab Notes"
  navbar:
    background: "#A9A9A9"
    google-analytics: "G-8SL8WKCMYZ"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hakyimlab/web-lab-notes-quarto
  search: 
    location: navbar
    type: overlay
    copy-button: true
  body-footer: |
      © [HakyImLab and Listed Authors](https://hakyimlab.org) - [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0/) - Code licensed under MIT
  
format:
  html:
    theme: cosmo
    css: styles.css


