---
title: PARG Fall Social 2022
author: Haky Im
date: '2022-10-20'
slug: parg-fall-social-2022
categories:
  - analysis
---

```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(glue))
PRE = "/Users/haekyungim/Library/CloudStorage/Box-Box/LargeFiles/imlab-data/data-Github/web-data"
##PRE="/Users/margaretperry/Library/CloudStorage/Box-Box/imlab-data/data-Github/web-data "
##PRE="/Users/temi/Library/CloudStorage/Box-Box/imlab-data/data-Github/web-data"
## COPY THE DATE AND SLUG fields FROM THE HEADER
SLUG="parg-fall-social-2022" ## copy the slug from the header
bDATE='2022-10-20' ## copy the date from the blog's header here
DATA = glue("{PRE}/{bDATE}-{SLUG}")
if(!file.exists(DATA)) system(glue::glue("mkdir {DATA}"))
WORK=DATA

## move data to DATA
#tempodata=("~/Downloads/tempo/gwas_catalog_v1.0.2-associations_e105_r2022-04-07.tsv")
#system(glue::glue("cp {tempodata} {DATA}/"))
##system(glue("open {DATA}")) ## this will open the folder 
```


```{r}
df <- readxl::read_excel(glue("{WORK}/report-2022-10-20T1314.xlsx"))
names(df)

df %>% count(`Campus affiliation  (dept/div) and role (undergrad, grad, staff, faculty, other)`) %>% arrange(desc(n))
```
<mark>not very helpful, better to have list to select from rather than free text next time</mark>

```{r}

df %>% count(`How did you hear about us?`) %>% arrange(desc(n)) 

```
<mark>I-house newsletter was the most effective dissemination</mark>

