---
title: how to apply to F30/31 grants
description: material collected by grad students at UChicago
author: Jennifer Blanc, Eric McIntire
date: 2024-07-11
---

Jennifer and Erik created this resource to help  graduate students in genetics (HG, GGSB, etc) navigate the process of applying to F30/31 grants. With examples.

> Hi everyone! 
@Erik McIntire
 and I have been working on a google drive that complies materials, instructions, and advice for applying to F30/F31 grants for genetics grad students. We both noticed that the instructions online aren’t always clear and it was extremely helpful for both of us to have examples to look at. We hope that others might be interested in adding materials to it, please contact one of us and we can add you to the drive as an editor! Otherwise we hope that its helpful for current grad students and can be passed down within the community!
 
[Google drive folder](https://drive.google.com/drive/folders/1yNAmJhyYF0hZal1zRP7Ps6R6zDej9RYj?usp=drive_link) with instructions, tips, and examples. You may need a Uchicago google account to access the material. Contact Jennifer and Eric directly if you need access with other accounts.
 
